# Step 1: Menggunakan Node.js base image
FROM node:14

# Step 2: Set working directory dalam container
WORKDIR /usr/src/app

# Step 3: Menyalin package.json dan package-lock.json untuk menginstal dependencies
COPY package*.json ./

# Step 4: Install dependencies
RUN npm install

# Step 5: Menyalin seluruh kode aplikasi ke dalam container
COPY . .

# Step 6: Menjalankan aplikasi ketika container dijalankan
CMD ["npm", "start"]

# Expose port untuk aplikasi
EXPOSE 3000
